# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "oss-ext-middleware"
BBFILE_PATTERN_oss-ext-middleware = "^${LAYERDIR}/"
BBFILE_PRIORITY_oss-ext-middleware = "7"

LAYERDEPENDS_oss-ext-middleware = "core oss-reference"
LAYERSERIES_COMPAT_oss-ext-middleware = "kirkstone"

require conf/include/package_revisions_oss_middleware.inc
