PR:pn-libnetfilter-log ?= "r0"
PACKAGE_ARCH:pn-libnetfilter-log ?= "${OSS_LAYER_ARCH}"

PR:pn-libnfnetlink ?= "r0"
PACKAGE_ARCH:pn-libnfnetlink ?= "${OSS_LAYER_ARCH}"

PR:pn-unbound ?= "r0"
PACKAGE_ARCH:pn-unbound ?= "${OSS_LAYER_ARCH}"

PR:pn-daemonize ?= "r0"
PACKAGE_ARCH:pn-daemonize ?= "${OSS_LAYER_ARCH}"

PR:pn-dns-conntrack-failover ?= "r0"
PACKAGE_ARCH:pn-dns-conntrack-failover ?= "${OSS_LAYER_ARCH}"

PR:pn-libnetfilter-conntrack ?= "r0"
PACKAGE_ARCH:pn-libnetfilter-conntrack ?= "${OSS_LAYER_ARCH}"
